---
name: R-hub

on:
  push:
    branches:
      - test-rhub-workflows

jobs:
  rhub:
    name: R-hub
    uses: insightsengineering/r.pkg.template/.github/workflows/rhub.yaml@test-rhub-workflows
    with:
      lookup-refs: |
        averissimo/pkg1
        averissimo/pkg3
